### ISSUE TITLE
UPS and FedEx Shipping Plugin current API integrations will break in June and May respectively

### ISSUE THREAD

**Issue by newlinewebdesign** [J2Store4/j2store4#94] opened 2024-03-19 17:01 UTC
Thanks for creating and supporting J2Store through the Joomla 4/5 transitions.  I am sure you and the team are aware, but in less than two months, the current J2Store Fedex shipping plugins will break if not updated and in June of this year, the same thing will occur to the UPS plugins. Is there going to be any updates to support the new OAuth 2.0 security model? 

Either way, I hope there can be a message displayed on the J2Store website to notify all the users on the status so everybody can plan accordingly and not be surprised when their stores stop generating revenue due to their shipping options not working anymore.

Here is the link to the UPS migration guide:
https://developer.ups.com/oauth-developer-guide?loc=en_US&sp_rid=Njk1MDkzMzczMzkwS0&sp_mid=74042688

Here is the link to the FedEx Developer:
https://developer.fedex.com/api/en-us/get-started.html?cmp=EMT-1005480-33-1-200-1110010-GLBL-US-EN-WSDLRETIRENOV00&ET_CID=1268974&ET_RID=54765631&LINK=FeDex_Developer_Portal&locale=EN-US

**Comment by mgopin3** [comment] 2024-03-21 09:34
@newlinewebdesign We would like to assure you that we are currently utilizing the latest APIs for both USPS and FedEx shipping plugins. Therefore, there is no need to worry about potential disruptions. Rest assured, we are committed to ensuring that your shipping options remain fully functional.Thank you for bringing this to our attention.

**Comment by newlinewebdesign** [comment] 2024-03-25 21:14
@mgopin3 Thank you for your reply. Are you aware that on May 15, FedEx is retiring their XML/SOAP based API that the current FedEx plugin uses and all users will need to create a new set of oath API credentials? The same thing is occurring for the UPS shipping plugin on June 3.

Both plugins are currently using these API's.  There are many of us that are concerned our shipping integrations will be cut off.  Can you confirm that won't be the case even though both carriers have been issuing warnings to contrary for the past 9 months?

**Comment by mgopin3** [comment] 2024-03-27 11:19
@newlinewebdesign We wish to confirm that we are currently employing the latest APIs for both USPS and FedEx shipping plugins. Consequently, you can rest assured that there will be no disruptions to your shipping services. If any latest APIs are released by these shipping plugins, we will promptly update our plugins and release a new plugin version. Your understanding is greatly appreciated.

**Comment by mgopin3** [comment] 2024-04-01 06:09
@newlinewebdesign We believe the reported issue has been addressed. Could you please confirm that the problem is resolved on your end? If everything looks good, we'll go ahead and close this issue.

If you have any further questions or if there's anything else you'd like assistance with, please don't hesitate to let us know. We appreciate your feedback!

**Comment by newlinewebdesign** [comment] 2024-04-01 12:41
The issue is not resolved as of yet. Fedex plugin needs to implement Oath2
by May and UPS by June. Looking at the latest plugins and they are using
access keys to connect. None of these will work for the respective plugins,
as it clearly states on their websites.
I'm not trying to be difficult, but simply saying that you are using the
latest api without acknowledging this major item makes me even more
concerned.

Do the current ups/ fedex plugins use oath2 to connect or are they still
using access keys to connect?

Adam

**Comment by mgopin3** [comment] 2024-04-04 07:11
@newlinewebdesign We would like to inform you that we are currently utilizing the latest OAuth authentication method for the FedEx shipping plugin, and for the USPS shipping advance plugin, we are following the most recent documentation provided by USPS. Therefore, there is no need to worry; we are committed to keeping our plugins up-to-date. Rest assured that if updated documentation is released by either shipping provider, we will promptly incorporate it into our plugins and release new versions accordingly. Your understanding and cooperation are greatly appreciated.

**Comment by newlinewebdesign** [comment] 2024-04-04 11:12
Thank you for your reply. USPS isn't an issue (yet), but can you confirm
the same for UPS?

**Comment by mgopin3** [comment] 2024-04-05 07:15
@newlinewebdesign We would like to inform you that the UPS app is currently not available for J2Store 4. Currently we have only  availability plugins Shipping USPS and FedEX shipping on j2store4, We are actively working on migrating and releasing the Plugins compatibility for J2Store 4 as soon as possible.

**Comment by mgopin3** [comment] 2024-04-05 07:18
@newlinewebdesign We regret to inform you that the UPS app is presently unavailable for J2Store 4. Currently, we offer availability plugins for Shipping USPS and FedEx shipping on J2Store 4. Please be assured that our team is diligently working on migrating and releasing plugin compatibility for J2Store 4 at the earliest convenience.

**Comment by newlinewebdesign** [comment] 2024-04-05 10:40
Would you like me to send you the J2Store 4 version? I have already
migrated it as well as the subscriptions plugin (and another 20 or so)?

Adam

**Comment by mgopin3** [comment] 2024-04-09 08:05
@newlinewebdesign We have successfully migrated several apps, modules, components, payment, and shipping plugins for compatibility with Joomla 4 alongside J2Store 4. If you would like to view and purchase our latest released plugin version 4.x.x, please visit the following link: [[Link](https://www.j2store.org/extensions/)].

**Comment by newlinewebdesign** [comment] 2024-04-15 21:30
mgopin3 I am not sure if this is a language issue or something else, **_but I have already updated many of the J2Store plugins that you have not released and I asked if you would like me to send them to you so you can review them and release as new j2store 4 plugins?_** I have migrated all 30 of my j2store sites over to Joomla 5 /J2store 4  and very familiar with where to find everything.

**Comment by Linkedla** [comment] 2024-04-19 00:47
Thank you, knowing that J2Stores is J5 ready is of great help!.

**Comment by mgopin3** [comment] 2024-04-22 10:39
@Linkedla I understand your concern. Currently, we have not tested J2Store 4 compatibility with Joomla 5. Please rest assured that we appreciate your feedback, and we will take note of it. In the near future, we plan to migrate and conduct thorough testing to ensure J2Store 4 is compatible with Joomla 5. This update will be included in an upcoming J2Store release. Thank you for your patience and understanding.

**Closed as completed** 2024-10-14 15:21 UTC
