### ISSUE TITLE
Where are the translations?

### ISSUE THREAD

**Issue by pirosoft** [J2Store4/j2store4#37] opened 2023-10-16 08:37 UTC
I can't find where to download the component translations. Old translations are not available on the site. Where are?

best regards

**Comment by mgopin3** [comment] 2023-10-18 10:26
I understand your concern. 
Just to confirm, are you interested in purchasing a multi-language option for your site? We'd like to inform you that currently, we only offer language support for J2Store3. Please rest assured that we value your feedback, and we are actively working on making languages available for all countries. As soon as we accomplish this, we will transition and release language compatibility for J2Store4. We will keep you updated on our progress.

**Comment by pirosoft** [comment] 2023-10-23 10:52
ok, i need for J2Store4, thanks.

**Comment by mariantanase** [comment] 2024-02-22 13:59
Hi, I need italian language for J2Store for Joomla 4. It's available ?

**Comment by mgopin3** [comment] 2024-03-05 04:50
@pirosoft @mariantanase We wish to update you on our current language support, which is currently exclusive to J2Store3. Your feedback is highly valued, and we are diligently working towards extending language support to encompass all countries. Once this goal is achieved, we will promptly transition and provide language compatibility for J2Store4. Stay assured that we will keep you informed of our progress as we continue to enhance our offerings.

**Comment by mgopin3** [comment] 2024-04-01 04:41
@pirosoft We believe the reported issue has been addressed. Could you please confirm that the problem is resolved on your end? If everything looks good, we'll go ahead and close this issue.

If you have any further questions or if there's anything else you'd like assistance with, please don't hesitate to let us know. We appreciate your feedback!

**Closed as completed** 2024-04-08 04:39 UTC
