### ISSUE TITLE
J2store issues with Joomla 4.4.1

### ISSUE THREAD

**Issue by tonamphong** [J2Store4/j2store4#66] opened 2023-12-28 01:44 UTC
Hi there,
I got many issues with J2store latest and Joomla 4.4.1(clean installation). Do you have a hotfix for these issues? I'm using PHP 8.1, it's fine with PHP 8.0
Screenshots below:

Installation issue:
![j2store-installation](https://github.com/J2Store4/j2store4/assets/2299347/0dd08325-b02f-4311-9be3-8b466e324fde)

J2store Cpanel(Components -> J2store)

![j1](https://github.com/J2Store4/j2store4/assets/2299347/7bc9ada2-8606-4d31-9fd6-41678e6b4a41)
![j2](https://github.com/J2Store4/j2store4/assets/2299347/0e1ef7dc-f60c-47f4-a4cb-3c1121f2cf16)
Front-end(live site)
![front-end](https://github.com/J2Store4/j2store4/assets/2299347/6646425d-e537-4d5c-b650-07e3ead3b1cd)

**Comment by mgopin3** [comment] 2023-12-29 07:37
I understand your concern. Upon checking your error message, this issue might be caused by using the old FOF library on your site. In this case, I suggest you download the latest FOF library using the provided link.[[FOF link.](https://github.com/J2Store4/fof/releases)] After completing the installation, this issue will be resolved. Additionally, we have verified on our site, ensuring there is no issue with our J2Store latest version or Joomla 4.4.1 version. For your reference:

[[video link.](https://www.awesomescreenshot.com/video/23638852?key=233bf1c838c58039c1377f9cab2d1f82)]

If you encounter any further difficulties or have additional questions, please feel free to reach out.

**Comment by tonamphong** [comment] 2023-12-29 08:20
Hi there,
Thanks for your support. I created a video about this case(clean J4 installation)
Here the dropbox link https://www.dropbox.com/scl/fi/nrkp64n1d8w2unarcc28q/J2store.mov?rlkey=z0kerjx3y94c6az37fxhodujp&dl=0
Note: Fof lib installed but it didn't work.
I'm using php version 8.1.24

**Comment by mgopin3** [comment] 2024-01-02 05:54
I appreciate your understanding. We would like to inform you that we have recently released the latest version, labeled as **"revAB17961"**. In light of this, we recommend using the provided link to download and install the most up-to-date fof library on your site. By completing this installation, the reported issue should be effectively resolved.
[[FOF link.](https://github.com/J2Store4/fof/releases/tag/revAB17961)]

**Comment by tonamphong** [comment] 2024-01-02 06:15
It did't work :)

This is my test site(clean J4 installation and J2store latest) https://www.dropbox.com/scl/fi/t1ryt3opxivjop0sk2waj/site-localhost-20240102-060820utc-mCsLSrY2s2S55FSN.zip?rlkey=mpjwo1qnrtzfs9mk74qt5hjrp&dl=0

Note: I just created a product to test and here the result
![j2store](https://github.com/J2Store4/j2store4/assets/2299347/f63fbb2e-f48f-4e6c-939c-f64213076442)

I'm using php 8.1.24, it works for php 7.4 and php 8.0 only

**Comment by mgopin3** [comment] 2024-01-08 05:23
I appreciate your understanding. We sincerely regret any inconvenience you may be experiencing on your end. Rest assured, we have duly noted this issue and are committed to addressing it in the upcoming J2Store4 release. For your reference, you can monitor the code changes in our J2Store4 commit #72  . Thank you for bringing this to our attention, and we assure you that it will be resolved promptly .

**Comment by tonamphong** [comment] 2024-01-08 07:43
Hi there,
Thanks for your support. I think most issues are fixed now, however, there's an issue with front-end still remaining:
Deprecated: strtolower(): Passing null to parameter #1 ($string) of type string is deprecated in /Users/dev/Sites/build/j2store/libraries/vendor/joomla/filter/src/InputFilter.php on line 213

**Comment by mgopin3** [comment] 2024-03-04 05:35
@tonamphong I appreciate your concern. Following the identification and reproduction of all deprecated issues on the J2Store 4 site, we have addressed and resolved these issues with the commit available at https://github.com/J2Store4/j2store4/pull/72. Additionally, if you encounter any deprecated issues on your J2Store 4, kindly provide a video reference demonstrating the steps to reproduce the issue. This will significantly assist us in resolving the matter for the upcoming J2Store release.

**Comment by mgopin3** [comment] 2024-05-09 07:46
@tonamphong Thankyou for your understand and patience.
we will consider your requirement as feedback, and we will incorporate it into our upcoming J2Store release. If everything looks good, we'll go ahead and close this issue.

If you have any further questions or if there's anything else you'd like assistance with, please don't hesitate to let us know. We appreciate your feedback!

**Closed as completed** 2024-05-20 04:40 UTC
