### ISSUE TITLE
API J2store

### ISSUE THREAD

**Issue by mehdininja** [J2Store4/j2store4#79] opened 2024-02-07 00:38 UTC
hi, How to connect to j2store through API and implement ordering and purchasing procedures in the Android application?

**Comment by mgopin3** [comment] 2024-02-08 05:16
I can understand your concern. We are sorry, but currently, we don't have an option to integrate an API with the Android application to process ordering and purchasing. In this case, we will take note of your requirement.

Before submitting a report on issue tracker #46, please review the provided instructions, as they specify the types of issues for which we can offer support. Issues outside the scope of these instructions will not be considered. We appreciate your understanding.

**Comment by mgopin3** [comment] 2024-03-04 04:24
@mehdininja We believe the reported issue has been addressed. Could you please confirm that the problem is resolved on your end? If everything looks good, we'll go ahead and close this issue.

If you have any further questions or if there's anything else you'd like assistance with, please don't hesitate to let us know. We appreciate your feedback!

**Comment by mehdininja** [comment] 2024-03-10 16:59
@mgopin3 Date of Release and creation date change to update date .
![jj](https://github.com/J2Store4/j2store4/assets/74552816/3f5f3f2d-f34e-4ab7-8b10-4bb858335c0b)
![jjj](https://github.com/J2Store4/j2store4/assets/74552816/214f255c-66c7-48d7-a40e-3996830d0d81)

Date of Release and creation date : 1402-10-01 After saving changed to 1402-12-18

**Closed as completed** 2024-03-12 04:27 UTC
