### ISSUE TITLE
Product Display Module

### ISSUE THREAD

**Issue by JoomFX** [J2Store4/j2store4#40] opened 2023-10-22 14:00 UTC
Hey guys,

When do you think you will have the [Product Display Module](https://docs.j2store.org/modules/product-display-module) Joomla 4 (and Joomla 5) compatible?
I see that currently only the Cart and Currency modules are [available in the repo](https://github.com/J2Store4/j2store4/tree/main/modules/site).

**Comment by mgopin3** [comment] 2023-10-27 02:14
Currently, the "Product Display Module" is not available on J2Store 4. We have deprecated all the plugins, apps, and modules for J2Store 3. However, we are actively working on migrating and updating them to be compatible with Joomla 4 with J2Store 4.0.3-PRO.

We have recently released several payment plugins and apps for J2Store, such as 'Stripe Checkout,' 'Authorize.net,' 'Mollie,' and more. You can find these releases on our website at this link: https://www.j2store.org/extensions/.

Rest assured, your satisfaction is our top priority, and we're dedicated to providing you with a seamless transition. Additionally, as soon as possible, we will release the "Product Display Module" for J2Store 4, ensuring you have access to all the essential features you need.

**Comment by pulsarinformatique** [comment] 2023-11-15 08:43
Hello
We badly need this module since it is a core feature of J2store. Again, if we need to pay for it we will do it
thanks

**Comment by pulsarinformatique** [comment] 2023-11-21 12:48
no answer ?

**Comment by ScaleBxl** [comment] 2023-11-28 11:48
I'm waiting for it too, I have 3 websites to update, and I can't because almost everything is based on this module.

**Comment by N8Solutions** [comment] 2023-11-28 17:19
Hello @mgopin3,

Can we get an update on this. I too, like the others here that have commented, have several sites that I need to upgrade to Joomla 4 and I'm unable to do so because this module is not available for J4/5.

**Comment by pulsarinformatique** [comment] 2023-11-30 07:17
It' s very weird that j2store team can't understand that this module is not that accessory. It could / should have be part of the core package.

**Comment by pulsarinformatique** [comment] 2023-12-04 07:12
Hi
Again the "by the end of the month" promise wasn't held. 
PLEASE what are your priorities ??

thanks

**Comment by N8Solutions** [comment] 2023-12-09 19:22
> Rest assured, your satisfaction is our top priority, and we're dedicated to providing you with a seamless transition. Additionally, as soon as possible, we will release the "Product Display Module" for J2Store 4, ensuring you have access to all the essential features you need.

@mgopin3 & @rameshelamathi can you guys, or someone else from your support team do something about putting a rush on this Display module? At least give us a response? Something??? The lack of responses from J2Store support is mind boggling! Communication is key to running any business!

I have several sites waiting on this module that can not be migrated to Joomla 4 until it is available! This issue was opened on Oct. 22nd, and the one and only reply from J2Store support was a week later on Oct. 27th. My clients really want to migrate their sites to Joomla 4 since J3 is EOL.

What I don't think you guys grasp is that our clients look to us for answers. When we were told this would be J4 ready, it was expected that all important features and modules would be as well. I had assured my clients they would be able to upgrade to Joomla 4 without any issues, and since that didn't happen it makes us look bad in the eyes of our clients! I've already lost a client because of this debacle and I don't want to lose any more! I've been extremely polite and patient, all things considering, but this has gone on for far too long especially when it starts costing me money due to lost clients.

You guys really need to get your house in order or no amount of work you do will be able to save J2Store from the grave it has dug itself!

**Comment by pulsarinformatique** [comment] 2023-12-09 19:26
yes, this lack of answer and even of customer support is unbearable.

**Comment by pulsarinformatique** [comment] 2023-12-13 07:32
Still nothing !!

**Comment by rameshelamathi** [comment] 2023-12-13 15:34
@pulsarinformatique @N8Solutions  We greatly appreciate your understanding and cooperation in this matter. It's important for us to clarify that our support is not extended through issue tracking. J2Store, including all its PRO features, is an open-source project, and we are dedicated to actively developing its core functionalities. However, given our small team, some modules might require additional time to perfect.

We kindly invite and encourage community contributions, as active support in fixing issues and enhancing features would be immensely beneficial. Unfortunately, at present, we haven't received much active community support in this regard.

Additionally, it's worth noting that there has been a significant decline in Joomla's adoption, which has affected our revenue from extension sales, making it challenging to cover costs. Despite these challenges, we remain steadfast in our commitment to maintain and continuously develop J2Store 4. We understand that progress takes time, and we're doing our best under the circumstances.

We are earnestly seeking volunteers from the community to assist with bug fixes and improvements. Your support and contributions would be highly valuable and appreciated.

**Comment by pulsarinformatique** [comment] 2023-12-13 16:09
hi Ramesh
This answer is not possible. When we asked you if you will continue to support J2store for Joomla4 the answer was definitively yes. you repeated that the module will be available each month.

I understand the joomla ecosystem issue, I really do but when we decided to migrate to J4 we asked you so that we could guarantee to our customers that we will be able to do it.

**Comment by rameshelamathi** [comment] 2023-12-13 16:27
@pulsarinformatique  I guess, you have missed a part of my response:
"Despite these challenges, we remain steadfast in our commitment to maintain and continuously develop J2Store 4. We understand that progress takes time, and we're doing our best under the circumstances."

**Comment by pulsarinformatique** [comment] 2023-12-13 16:30
No I didn't miss it, this is simply a non significant part of your mail since it is a copy/paste of the same answer we have been receiving for months now.
I'm sure you are sincere but our customers don't care :)

**Comment by N8Solutions** [comment] 2023-12-14 11:13
@rameshelamathi (@mgopin3) I was one of your biggest supporters and champions after Joomla 4 was released. I had a Pro Developer license for many years. When I emailed or opened a ticket regarding Joomla 4 compatibility, you or your team always responded quickly. As time went on, communication became more of a problem. My first communication about Joomla 4 compatibility was Nov. 7th, 2021, and I received a reply the very next day that stated the following:

> Hi ,
> Thank you for reaching out to us. This is Chanchal from J2Store Team.
> We are working on hard to bring in J2Store4 as soon as possible. 
> Since there are a number of breaking changes and J2Store having over 200+ plugins (payment, shipping, apps), it is taking us quite sometime...
> Any change we make will require checking compatibility between Joomla 3 and Joomla 4, and 200+ extensions...  Hope you can imagine... 
> While we have completed migrating the J2Store core, the extension migration is taking time.. . We do not have a definite ETA... **but we are looking to roll out by February or March 2022**.

**If you see at the end I was notified that you would be rolling out the Joomla 4 compatible version in February or March of 2022!** Every "milestone" you set was pushed back again and again. I have plenty more email exchanges saved that highlight the delays. You pinned [an issue](https://github.com/J2Store4/j2store4/issues/60#issue-2040026408) to point out that you no longer provide support. The fact is, many of us were paid subscribers and had expectations, based on our correspondence with you, that J2Store would be fully compatible with Joomla 4 along with it's extensions, and in the end you and your team not only let us down, you've made us look bad to our customers because you were unable to meet the milestones you set. On top of that, your communications were misleading because you never once mentioned that you would be moving to an open source model once you released the Joomla 4 Compatible version of J2Store, and that you would stop offering support. There isn't even a way to purchase a support subscription! If money is an issue, add an option to purchase support on your site. Please understand where our frustration is coming from. On top of everything else, when you finally released the Joomla 4 version, there were no extensions to go with it so it was essentially worthless to anyone already using J2Store with extra extensions.

You also mentioned the following in your reply above:

> We kindly invite and encourage community contributions, as active support in fixing issues and enhancing features would be immensely beneficial. Unfortunately, at present, we haven't received much active community support in this regard.
> 
> Additionally, it's worth noting that there has been a significant decline in Joomla's adoption, which has affected our revenue from extension sales, making it challenging to cover costs.

It's my opinion the reason for this lack of support from the community and lack of adoption isn't directly related to any decline in the use of Joomla but rather a lack of faith in your company to deliver what is promised based on how you handled the rollout of the Joomla 4 compatible version because the release was so significantly delayed coupled with the lack of communication. I read many discussions where developers saw the delays and and lack of responses to inquiries and made the decision to move to a different Ecommerce extension for Joomla because they couldn't wait any longer.

I meant what I wrote above, because of the way the rollout of your Joomla 4 compatible version was handled, your company has one foot in the grave. If you are going to survive this, you need to A) start taking responsibility for what happened and stop deflecting & B) start being more responsive to issues that are posted here as most of them aren't support requests. Being silent, or doing the bare minimum research for an issue only leaves a bad taste in the mouth of your users, especially those of us who were long time supporters and users of your software. If an issue is opened that is a support request, simply state it as such and close the issue. If it is not a support request, acknowledge it so we know you are actively working on this. Maybe you should consider creating a "Gitter" chat room or adding a forum to your website where your users could support each other with help from you team from time to time. Gantry 5 has a Gitter chat room which is not as active as it once was, but it was at one time thriving when they had initially released Gantry 5 and therefore there were a lot of questions. The forum on their website is still very busy with lots of activity. This is just some advice from an outside perspective that I believe would go a long way in helping you business.

You and your team can do better, and you know it. I believe you guys had a great product, and that it can be great again, but you need to take this for what it is, **constructive criticism**, from someone that was a big supporter but who now feels let down by the way things were handled.

Regards

**Comment by mgopin3** [comment] 2023-12-15 06:00
@JoomFX @pulsarinformatique @ScaleBxl Thank you for your patience and understanding over the past month. We are pleased to inform you that we have recently released several modules, including the product display module, search module, category module, and related product module. If you are interested in purchasing our latest modules, please find the link to view the latest releases and make a purchase here:- https://www.j2store.org/downloads/category/modules/

**Comment by N8Solutions** [comment] 2023-12-15 08:40
@mgopin3 I hope it was just an oversight on your part that you didn't tag/mention me in your comment, and that my **constructive criticism** posted in this thread hasn't offended or upset you or your team.

In any case, thank you for posting here that the Product Display Module is ready for Joomla 4.

regards

**Comment by pulsarinformatique** [comment] 2023-12-18 07:10
Thanks a lot for having released the display module for j4
We will test it and report issues if found
thanks again

**Comment by ScaleBxl** [comment] 2023-12-19 12:44
Bad link to product page with Product Display Module

, instead of

"MYSITE/products/product_xxx" I have this link

"MYSITE/component/j2store/products/product_xxx"

(this one takes me back to the home page every time, instead of the product page)

Am I the only one having this problem?

[Bienvenue_sur_-_Made_in_Asturies_—_Mozilla_Firefox_2023-12-19_13-31-55.webm](https://github.com/J2Store4/j2store4/assets/149295599/b4376b11-ef26-4a8d-97d2-d02f0b6372a7)

**Comment by mgopin3** [comment] 2023-12-26 06:35
@ScaleBxl  Thank you for your patience. After reviewing the video reference, it appears that you are using multiple languages on your site. In this case, you need to create the same product for each language used on your site. Typically, when you click on a product in the product display module, if there is a product available in that language, it will redirect to the respective product page. If not, it will redirect to the home page. Please make sure to create a product for each language.After completing this, the issue will be resolved.

**Comment by mgopin3** [comment] 2024-03-05 04:48
@ScaleBxl We believe the reported issue has been addressed. Could you please confirm that the problem is resolved on your end? If everything looks good, we'll go ahead and close this issue.

If you have any further questions or if there's anything else you'd like assistance with, please don't hesitate to let us know. We appreciate your feedback!

**Closed as completed** 2024-03-12 04:36 UTC
