### ISSUE TITLE
Fix Bug customers.php

### ISSUE THREAD

**Issue by mehdininja** [J2Store4/j2store4#83] opened 2024-02-17 20:28 UTC
![145](https://github.com/J2Store4/j2store4/assets/74552816/a202daf0-e85d-4179-b896-64bde45ec327)

![144](https://github.com/J2Store4/j2store4/assets/74552816/671e7d2a-fb64-4932-a7d1-43dd61d6bd1c)

**administrator/components/com_j2store/controllers/customers.php**

`$state['customer_name'] = $app->input->getstring('customer_name',''); `

and

```
'customer_name' => array(
                'type' => 'fieldsearchable',
                'sortable' => 'true',
                'show_link' => 'true',
                'url' => "index.php?option=com_j2store&amp;view=customer&amp;task=viewOrder&amp;email_id=[ITEM:ID]",
                'url_id' => 'email',
                'label' => 'J2STORE_CUSTOMER_NAME'
            ),
```

**change "customer_name" to  "first_name"**

`$state['first_name'] = $app->input->getstring('first_name','');`

. . .

```
'first_name' => array(
                'type' => 'fieldsearchable',
                'sortable' => 'true',
                'show_link' => 'true',
                'url' => "index.php?option=com_j2store&amp;view=customer&amp;task=viewOrder&amp;email_id=[ITEM:ID]",
                'url_id' => 'email',
                'label' => 'J2STORE_CUSTOMER_NAME'
            ),
```

**Comment by mgopin3** [comment] 2024-02-19 02:24
We would like to inform you that we typically retrieve customer name inputs and display the custom name field in JStore under Sales -> Customers on both J2Store3 and J2Store4. Upon checking the admin backend on our site, we observed that the customer name is being displayed without any issues.

If you wish to display the customer's first name instead of the customer name input in the customer name field, you can achieve this by creating a template override for that file on your site. For your reference, please review the attached image [[image](http://tinyurl.com/29wjmctl)]

**Comment by mgopin3** [comment] 2024-03-01 11:24
@mehdininja We believe the reported issue has been addressed. Could you please confirm that the problem is resolved on your end? If everything looks good, we'll go ahead and close this issue.

If you have any further questions or if there's anything else you'd like assistance with, please don't hesitate to let us know. We appreciate your feedback!

**Closed as completed** 2024-03-12 04:26 UTC
