### ISSUE TITLE
Stripe Checkout - HTML striped from text fields

### ISSUE THREAD

**Issue by PixedBo** [J2Store4/j2store4#32] opened 2023-10-03 15:17 UTC
Hello, i'm using stripe checkout and it's working. Only problem i'm facing is in the plugin configuration where you can find the fields "text after payment", "text after cancellation", ...
If I put inside HTML tag such as < br/ > or < a href="" > or < b > < /b > (without the spaces, of course) they are automatically canceled so i can only write some plain text. Is possible to remove the "clearing" automation of the fields?
Thanks!

**Comment by mgopin3** [comment] 2023-10-11 01:20
I understand your concern. Yes, we have restricted the use of HTML content in the payment display text for selection, before and after payment. As a result, any HTML content applied to the payment display text will be converted into plain text. Please don't worry about this limitation. If you wish to implement HTML content in the payment display text, it is possible through a language override. You can create a language override for the HTML content you'd like to display as text for your payment action. After creating a language override, you will receive a Language Constant text. You can then use this Language Constant in your payment display text for selection, before and after payment, wherever you'd like. This process will help you achieve your desired result.

Hope it will help you.

**Comment by mgopin3** [comment] 2024-03-05 04:54
@PixedBo  We believe the reported issue has been addressed. Could you please confirm that the problem is resolved on your end? If everything looks good, we'll go ahead and close this issue.

If you have any further questions or if there's anything else you'd like assistance with, please don't hesitate to let us know. We appreciate your feedback!

**Closed as completed** 2024-03-12 04:36 UTC
