### ISSUE TITLE
Bug in myprofile (Problem with entering incorrect data)

### ISSUE THREAD

**Issue by mehdininja** [J2Store4/j2store4#88] opened 2024-03-10 01:39 UTC
hi,
When we enter wrong data **(In guest form)**, it is go to page index.php/myprofile/**guestentry** and gives the following error 

![j2s1](https://github.com/J2Store4/j2store4/assets/74552816/604b2188-c313-4c64-a9ff-9fcc1b4cda3f)
![j2s2](https://github.com/J2Store4/j2store4/assets/74552816/8a0a07ba-0db3-45fa-b53b-80c5a954c5d5)

test in joomla 4.4.3

**Comment by mgopin3** [comment] 2024-03-12 07:11
@mehdininja Thank you for bringing this issue to our attention. Please rest assured that we have taken note of this issue concern. We are committed to addressing and resolving this issue in the upcoming J2Store 4.x.x release. For your reference, you can review the code changes associated with this fix on our J2Store 4 repository #89

**Comment by mgopin3** [comment] 2024-03-12 07:12
@mehdininja We believe the reported issue has been addressed. Could you please confirm that the problem is resolved on your end? If everything looks good, we'll go ahead and close this issue.

If you have any further questions or if there's anything else you'd like assistance with, please don't hesitate to let us know. We appreciate your feedback!

**Closed as completed** 2024-03-18 04:33 UTC
