### ISSUE TITLE
Unable to download and install more languages

### ISSUE THREAD

**Issue by PixedBo** [J2Store4/j2store4#28] opened 2023-09-29 07:03 UTC
Hello, i am unable to download additional languages.
Here (https://www.j2store.org/translations/) there is a "Read this guide for more information" that is not a link, if i click on the green button i'm redirected to this page (https://explore.transifex.com/j2store/j2store3/) that have translations for version 3 and (maybe it's me, and i don't know how transifex works) i can't click anywhere and download the needed translation.
Thanks

**Comment by mgopin3** [comment] 2023-10-06 11:56
I can understand your concern.
We would like to inform you that currently, we only have language availability for J2Store3. Please rest assured that we appreciate your feedback, and we are actively working on making languages available for all countries. As soon as we achieve this, we will migrate and release language compatibility for J2Store4. We will keep you informed of our progress.

**Comment by mgopin3** [comment] 2024-03-05 04:56
@PixedBo  We believe the reported issue has been addressed. Could you please confirm that the problem is resolved on your end? If everything looks good, we'll go ahead and close this issue.

If you have any further questions or if there's anything else you'd like assistance with, please don't hesitate to let us know. We appreciate your feedback!

**Closed as completed** 2024-03-12 04:51 UTC
