### ISSUE TITLE
Call to undefined method Joomla\CMS\Application\AdministratorApplication::isAdmin() after migrating to J4

### ISSUE THREAD

**Issue by momchilcho** [J2Store4/j2store4#18] opened 2023-09-09 11:51 UTC
After carefully following your process and making sure that the migration checker was all green I managed to update to J2S 4 however once I updated to J4 I am unable to access the backend nor the products on the front end.

**Comment by mgopin3** [comment] 2023-09-11 05:16
I can understand your concern.

Please be informed that this issue might be caused by using an outdated version of the FOF library on your site. In this case, I recommend that you install the latest version of the FOF library. After installing the latest version of the FOF library, please attempt to install the latest release of J2Store v4 (4.0.2-Pro) on your site.

By completing these steps, the issue should be resolved. If you continue to experience the same issue on your site, please don't hesitate to let us know. Please enable the debug mode and send a reference image for the issue that you are facing.

You can download the latest version of the FOF library https://github.com/J2Store4/fof/releases

**Comment by landed1** [comment] 2023-09-16 11:46
Should we run the migration while in J3. I did not this time round and have FOF issues. J4 doesn't use it from what I can tell.
Now I can't uninstall J2store. Any ideas?

**Comment by Thomastomy2001** [comment] 2023-09-20 12:28
Hi landed1,

Please utilize Joomla 3 site backup to create a new Joomla 3 and J2Store 3 site. Afterward, perform the migration from J2Store 3 to J2Store 4 in Joomla 3 using the J2Migration component. Please review the provided documentation as it contains valuable information to assist with the migration process (https://docs.j2store.org/migration-from-j2store-3-to-4).

Alternatively, you must set up a new site for J2Store 4 with Joomla 4. Unfortunately, it's not possible to retrieve the old data in this scenario.

**Comment by mgopin3** [comment] 2024-03-05 05:19
@landed1 @momchilcho We believe the reported issue has been addressed. Could you please confirm that the problem is resolved on your end? If everything looks good, we'll go ahead and close this issue.

If you have any further questions or if there's anything else you'd like assistance with, please don't hesitate to let us know. We appreciate your feedback!

**Closed as completed** 2024-03-12 04:36 UTC
