### ISSUE TITLE
How do I remove the migration checker?

### ISSUE THREAD

**Issue by skurvish** [J2Store4/j2store4#75] opened 2024-01-13 13:25 UTC
After I have successfully upgraded from V2 to V3 when I try to remove the Migration Checker I get the following:

You are using an latest version of J2Store. No need to migrate
Extension Uninstall: Custom install routine failure.

The extension does not uninstall.

Is there something else I need to do?

**Comment by mgopin3** [comment] 2024-01-16 07:44
We appreciate your concern. We are sorry to hear that you are facing an issue on your site. Please be assured that we have taken note of this matter and have addressed it promptly. The latest version, 1.0.3, has been released to resolve this issue. You can view the release migration checker using the following link: [[Link to the latest release migration checker](https://github.com/J2Store4/j2store_migration_checker/releases)] In this regard, we recommend checking our commit code changes at the GitHub repository: [[Link to the specific commit code changes](https://github.com/J2Store4/j2store_migration_checker/commit/0fbecbb692d3a0fec7948c137c879cdad94cc337)] By implementing the same code changes on your site as per the provided commit, this issue should be resolved, and you will be able to uninstall the migration checker component successfully.

**Comment by skurvish** [comment] 2024-01-16 12:44
Yes, thankyou. This version solved the problem of uninstalling the migration checker. Well done!

**Comment by mgopin3** [comment] 2024-03-04 05:23
@skurvish We believe the reported issue has been addressed. Could you please confirm that the problem is resolved on your end? If everything looks good, we'll go ahead and close this issue.

If you have any further questions or if there's anything else you'd like assistance with, please don't hesitate to let us know. We appreciate your feedback!

**Comment by skurvish** [comment] 2024-03-04 07:15
Yes, you can close this issue. Thanks.
________________________________

**Closed as completed** 2024-03-12 04:29 UTC
