### ISSUE TITLE
Different totals in the dashboard and in report

### ISSUE THREAD

**Issue by PixedBo** [J2Store4/j2store4#78] opened 2024-02-06 09:57 UTC
Hello, i see different values in dashboard and in reports. What is the correct value?
In dashboard i have two different values:

![dsahboard](https://github.com/J2Store4/j2store4/assets/12549961/691adee3-ccdd-4ff7-bb60-149aa7ee85d4)

Then in reports (i don't have sale report but only "report products") i see a third value:

![report2](https://github.com/J2Store4/j2store4/assets/12549961/73025c68-567b-48db-ad68-d32002f0c9db)

Which is the correct one? And what are the other values?

**Comment by mgopin3** [comment] 2024-02-07 12:30
I understand your concern. 
We have checked and confirmed that the total amount of orders is being calculated and displayed on the dashboard without any issues on our site. For your reference, please check this image:http://tinyurl.com/2xqjtoug

Before submitting a report on issue tracker https://github.com/J2Store4/j2store4/issues/46, please review the provided instructions, as they specify the types of issues for which we can offer support. Issues outside the scope of these instructions will not be considered. We appreciate your understanding.

**Comment by PixedBo** [comment] 2024-02-07 12:42
Thanks for your answer but the site Is just a plain Joomla and j2store with stripe plugin, nothing else. What can disrupt the totals like that?
It's important for us to have the right amounts in order to sent the totals to calulate taxes...

**Comment by PixedBo** [comment] 2024-02-07 20:52
Solved the mystery: i've downloaded all the sales and do the math via excel. The big red number shows only the COMPLETED orders. The total order under the "statistics" sections shows the COMPLETED orders plus the "incomplete" and "new orders" so it's a bit confusing becouse it adds also sales that did not actualy happened.

**Comment by mgopin3** [comment] 2024-03-04 04:53
To ascertain whether you wish to include and exhibit all types of order statuses on the dashboard at all times, kindly follow these steps to configure the order status to be counted and displayed:

1.Navigate to 'System' > 'Administrator Modules' and search for the 'J2Store Stats Mini' module.
Within the 'J2Store Stats Mini' module, locate the 'Status' option. Select the desired status (e.g., 'confirmed' or 'processed') for which you intend to calculate the total amount to be displayed on your admin dashboard.
2.Save the changes.
Should you have any questions or require further assistance, please feel free to reach out.

**Comment by mgopin3** [comment] 2024-03-12 04:41
@PixedBo We believe the reported issue has been addressed. Could you please confirm that the problem is resolved on your end? If everything looks good, we'll go ahead and close this issue.

If you have any further questions or if there's anything else you'd like assistance with, please don't hesitate to let us know. We appreciate your feedback!

**Closed as completed** 2024-03-21 09:45 UTC
