### ISSUE TITLE
J2Store v4.03 pro Apps menu Get Apps button transfers to 404 error page

### ISSUE THREAD

**Issue by exlemor** [J2Store4/j2store4#31] opened 2023-10-01 23:20 UTC
When you are in the Apps tab in J2Store v4.03pro version, and you scroll to the bottom, and you click on Get Apps button:

it sends you immediately to:
http://www.domainname.com/administrator/index.php?option=com_j2store&view=apps --->

https://www.j2store.org/extensions/apps.html?utm_source=pro&utm_medium=component&utm_campaign=inline&utm_content=apps

and you get a 404 error :/

![screenshot_2343](https://github.com/J2Store4/j2store4/assets/2597232/3b6994cd-cf50-4690-951d-aafd0d4eea81)

**Comment by mgopin3** [comment] 2023-10-06 11:02
We understand your concern and apologise for the inconvenience you're facing. We've recently removed the App store from J2StoreV4, which may have led to the 404 page redirection. If you'd like to download the latest updated plugins, you can directly access them from our official J2Store website. Please be assured that we will take this issue as feedback and work on resolving it in our upcoming J2Store updates.

**Comment by mgopin3** [comment] 2024-03-05 04:55
@exlemor  We believe the reported issue has been addressed. Could you please confirm that the problem is resolved on your end? If everything looks good, we'll go ahead and close this issue.

If you have any further questions or if there's anything else you'd like assistance with, please don't hesitate to let us know. We appreciate your feedback!

**Closed as completed** 2024-03-12 04:51 UTC
