### ISSUE TITLE
Zones are not set correct the land

### ISSUE THREAD

**Issue by skaysurfer** [J2Store4/j2store4#120] opened 2024-08-12 14:52 UTC
I have only germany, and activated zones - but the form only shows zones of USA

**Comment by mgopin3** [comment] 2024-08-19 07:31
@skaysurfer We have reviewed the site and can confirm that the zone is displaying correctly for Germany without any issues. For your reference, please see the attached video: [[video](https://www.awesomescreenshot.com/video/30623728?key=fda82ba496d1bea278610a9f11844029)]. If you continue to experience any challenges, we recommend submitting a support ticket to the J2Store support team. Kindly include your **admin** login credentials and **FTP** information to ensure a quicker resolution on our end.

**Comment by mgopin3** [comment] 2024-08-20 12:10
@skaysurfer We have successfully resolved the issue on your site as per the ticket you raised. Now, the zone will change based on the selected country without any issues.For your referene check your ticket [[Link](https://j2store.freshdesk.com/a/tickets/37995)] Thank you for your understanding.

We believe the reported issue has been addressed. Could you please confirm that the problem is resolved on your end? If everything looks good, we'll go ahead and close this issue.

If you have any further questions or if there's anything else you'd like assistance with, please don't hesitate to let us know. We appreciate your feedback!

**Closed as completed** 2024-08-26 05:21 UTC
