### ISSUE TITLE
PDF invoice

### ISSUE THREAD

**Issue by mariantanase** [J2Store4/j2store4#87] opened 2024-02-25 13:53 UTC
On the previous J2Store3 version was available some extra extensions, like PDF Invoice.
Will be available those extensions for j2store4 ?
Or you can provide detailes on how to create/customize a PDF template/invoice ?
Thanks

**Comment by mgopin3** [comment] 2024-02-26 01:24
We are pleased to inform you that we have successfully migrated and released the PDF Invoice App with compatibility for Joomla 4 and J2Store 4. If you are interested in utilizing our latest plugin on your Joomla 4 site, please find the link below to view and purchase the plugins:[[Link](https://www.j2store.org/extensions/)]
Please note that our latest released plugin is specifically designed for compatibility with Joomla 4 and J2Store 4.

**Note:-** Before submitting a report on issue tracker https://github.com/J2Store4/j2store4/issues/46, please review the provided instructions, as they specify the types of issues for which we can offer support. Issues outside the scope of these instructions will not be considered. We appreciate your understanding.

**Comment by mgopin3** [comment] 2024-03-01 11:19
@mariantanase We believe the reported issue has been addressed. Could you please confirm that the problem is resolved on your end? If everything looks good, we'll go ahead and close this issue.

If you have any further questions or if there's anything else you'd like assistance with, please don't hesitate to let us know. We appreciate your feedback!

**Closed as completed** 2024-03-12 04:25 UTC
