### ISSUE TITLE
J2Store breaks Joomla search

### ISSUE THREAD

**Issue by JoomFX** [J2Store4/j2store4#85] opened 2024-02-19 19:45 UTC
Hi guys,

In Joomla 4, the "**Search - J2Store**" plugin breaks the Joomla Search functionality.
Here, please have a look at [this video](https://youtu.be/SVWGIXSH6aw) that I recorded for you.

In this case I am talking about **com_search**, which is still officially supported and can be download from [here](https://github.com/joomla-extensions/search/releases/tag/4.1.0).
But the **com_finder** extension is broken as well. It does not show an error message but it always shows "0 results found" which is not correct.

Please fix the search functionality (both **com_search** and **com_finder**) because it is a crucial functionality for any website.

**Comment by mgopin3** [comment] 2024-02-26 02:59
I can understand your concern.
Upon reviewing your reported issue, we have determined that the product search module functions correctly when our search-j2store plugin is enabled. Our attempts to reproduce the problem were unsuccessful. It appears that the "0 results found" message you mentioned may be due to either not selecting a category in the [Categories to search *] option or attempting to search for a product outside the chosen category.

To assist you further, we recommend checking the instructional video provided for reference:- [[video](https://www.awesomescreenshot.com/video/25263618?key=fdbc9ee98dc2106daa9b7b60ac72c285)]. If the issue persists, we kindly request you to submit a ticket to the j2store support team. In order to expedite the resolution process, please include your admin login details and FTP information. This will enable us to investigate and address the issue more effectively from our end.

**Comment by mgopin3** [comment] 2024-03-01 11:22
@JoomFX We believe the reported issue has been addressed. Could you please confirm that the problem is resolved on your end? If everything looks good, we'll go ahead and close this issue.

If you have any further questions or if there's anything else you'd like assistance with, please don't hesitate to let us know. We appreciate your feedback!

**Comment by JoomFX** [comment] 2024-03-03 14:17
@mgopin3 You are testing/showing the "J2Store Product Search" module while the issue I report is related to the native Joomla Search - the Search module together with the Search Results page.

Please watch carefully [this new, very detailed video](https://youtu.be/F1DEMvqjTX8) that I recorded for you.
It compares how the native Joomla Search works on Joomla 3 and how it "works" on Joomla 4.

Please take your time and watch the whole video carefully.
You will see for yourself that this is indeed a J2Store issue.
You will also see all the steps that you need to perform in order to reproduce the problem.

And as I said in my first comment, this issue is reproducible with both the **com_search** and **com_finder**.

**Comment by mgopin3** [comment] 2024-03-04 02:02
@JoomFX Upon reviewing the provided video, it has come to our attention that the **route.php** file path included is incorrect on Joomla 4, indicating the existence of an issue on your site. Please be assured that we have duly noted this matter and plan to address it in an upcoming J2Store release. Meanwhile, to rectify this issue on your site, we kindly request you to submit a ticket to the J2Store support team. To expedite the resolution process, please include your **administrative login** details and **FTP** information. This will facilitate our investigation and allow us to address the issue more effectively from our end.

**Comment by JoomFX** [comment] 2024-03-04 09:37
@mgopin3 

> _Please be assured that we have duly noted this matter and plan to address it in an upcoming J2Store release._

Thank you for realizing that it is a bug in the J2Store component and for your commitment to fix it in the next release.

You can easily reproduce the issue yourself, but I understand that it will save you some time to look at an already configured website.
Please let me know where to send you a link so you can download the Quickstart package (Akeeba backup) of the website from my video. You said to submit a support ticket but I don't know where is the place for that, and the only thing I need is an email address where I can send the download link to.

**Comment by mgopin3** [comment] 2024-03-07 09:44
To raise a ticket with our J2Store support team, please use the following link: [Ticket](https://my.j2store.org/my-account/priority-ticket-system.html). Kindly include your administrative login details and FTP information in the ticket. This information will assist in our investigation and enable us to address the issue more effectively from our end.

**Comment by JoomFX** [comment] 2024-03-07 13:16
@mgopin3 It is getting a bit ridiculous here. Let me explain why:

1. This issue reports a bug in your software.
2. I agreed to send you a copy of the website (Akeeba backup) so I can **make it easier for you** to figure out where the problem comes from.
3. You are forwarding me to your **Paid** Ticketing System. How come?

Look, I do not have a problem with my website.
I am the developer of the Delight template and I am reporting a bug in your software.
I do not need you to look at my website.

Anyway, if you want me to send you a copy of the Delight template (Akeeba backup), please contact us by filling out the contact form here:

https://www.inspiretheme.com/contact-us

**Comment by mgopin3** [comment] 2024-03-08 05:40
@JoomFX We apologize for the issue you are facing on your end. This problem is caused by an incorrect route file path included in the search plugin. To resolve this, please follow these steps: Navigate to **/plugins/search/j2store/j2store.php.** Go to line number 10.
After completing these code changes, the issue should be fixed. Please verify the resolution with these modifications.

**Old code:-** 
     require_once JPATH_SITE . '/components/com_content/router.php';
**New code:-** 
        //require_once JPATH_SITE . '/components/com_content/router.php';
        $com_path = JPATH_SITE.'/components/com_content/';
        if (!class_exists('ContentHelperRoute')) {
            require_once $com_path.'helpers/route.php';
        }
        if (!class_exists('ContentRouter')) {
            if (version_compare(JVERSION, '3.99.99', 'lt')) {
                include $com_path . 'router.php';
            }
        }

**Comment by mgopin3** [comment] 2024-03-22 11:57
@JoomFX We believe the reported issue has been addressed. Could you please confirm that the problem is resolved on your end? If everything looks good, we'll go ahead and close this issue.

If you have any further questions or if there's anything else you'd like assistance with, please don't hesitate to let us know. We appreciate your feedback!

**Closed as completed** 2024-03-28 04:58 UTC
