### ISSUE TITLE
Booking App

### ISSUE THREAD

**Issue by ScaleBxl** [J2Store4/j2store4#71] opened 2024-01-02 17:19 UTC
Good morning,
I would like to know the status of the booking app update, I'm waiting it to update another website!

Thank you

**Comment by mgopin3** [comment] 2024-01-03 07:22
I understand your concern. We would like to inform you that the Booking app is currently not available for J2Store 4. We are in the process of migrating compatibility for J2Store 4 with Joomla 4. Please rest assured that we have taken note of this issue and have assigned it high priority. We are actively working on migrating and releasing the booking app compatibility for J2Store 4 as soon as possible.

**Comment by mgopin3** [comment] 2024-03-22 11:34
@ScaleBxl We believe the reported issue has been addressed. Could you please confirm that the problem is resolved on your end? If everything looks good, we'll go ahead and close this issue.

If you have any further questions or if there's anything else you'd like assistance with, please don't hesitate to let us know. We appreciate your feedback!

**Comment by ScaleBxl** [comment] 2024-03-23 07:58
Why ?Did you udated the booking app? I don't see it on your website.

Without this app I can't udate my website, so the problem still open

**Comment by mgopin3** [comment] 2024-03-28 05:23
@ScaleBxl 
We appreciate your understanding. Just to reiterate, at the moment, the Booking app isn't compatible with J2Store 4. We're diligently working on migrating compatibility to ensure it aligns seamlessly with Joomla 4. Rest assured, addressing this is a top priority for us. We're actively engaged in the process and aim to release the updated version for J2Store 4 as swiftly as we can.

**Comment by ScaleBxl** [comment] 2024-04-28 11:56
Good morning,

Is there any progress in updating the booking app?
I'm starting to have difficulties with my site and the PHP version. On the product page I get a blank page, I had to deactivate my .htaccess file.
The security of my store is truly compromised!

**Comment by mgopin3** [comment] 2024-05-07 08:03
@ScaleBxl We greatly value your understanding and patience. Rest assured, we are dedicatedly working on ensuring seamless compatibility with Joomla 4. Addressing this issue remains our top priority, and we are fully committed to expediting the process. We are actively engaged in the migration efforts and endeavor to release the updated version for J2Store 4 as swiftly as possible

**Comment by davidspring** [comment] 2024-06-26 05:17
I am wondering if you can provide an estimated date when the updated booking app will be available to test.

**Comment by ScaleBxl** [comment] 2024-06-26 06:28
They will just thank you for your patience, I opted for another solution.

**Comment by mgopin3** [comment] 2024-08-21 05:46
@davidspring  At this time, we do not have an exact release date for the Booking app. However, please rest assured that we are prioritizing your requirements, and we will migrate and release the plugin, fully compatible with J2Store 4 and Joomla 4, as soon as possible.

**Closed as completed** 2024-10-14 15:21 UTC
