### ISSUE TITLE
Standard Shipping methods not visible in backend

### ISSUE THREAD

**Issue by Kris3D** [J2Store4/j2store4#114] opened 2024-06-30 20:32 UTC
When I create Standard Shipping methods they do not appear in the Joomla backend.
They are however applied on the front end. Since I can't see the methods, I can't edit them.

Running j2store4 4.0.5 on Joomla 5 with Joomlart Purity IV template.

**Comment by mgopin3** [comment] 2024-07-01 09:44
@Kris3D In the event that you continue to encounter any challenges, I recommend submitting a support ticket to the J2Store support team. Please include your **admin login** details and **FTP** information for a more efficient resolution from our end.

**Comment by Kris3D** [comment] 2024-07-01 12:09
> @Kris3D In the event that you continue to encounter any challenges, I recommend submitting a support ticket to the J2Store support team. Please include your **admin login** details and **FTP** information for a more efficient resolution from our end.

How do I do that? On their site there is no support forum or e-mail available.

**Comment by Kris3D** [comment] 2024-07-01 14:40
Did a reïnstall and that did not help. When creating a shipping method under 'Standard Shipping methods' without enabling, I can see the method in the list. After enabling the method disappears from the list but is in the database and working on the frontend.

**Comment by mgopin3** [comment] 2024-07-02 07:26
@Kris3D 
If there are any concerns or technical difficulties, you can raise a support ticket by utilizing the email address associated with your purchase. Kindly use [support@j2store.org](mailto:support@j2store.org) for this purpose.

**Comment by Kris3D** [comment] 2024-07-02 10:49
Purchase? J2Store is free to use.
What are you talking about?

I think it is a bug in de software and therefore it belongs in the Issues.

Op di 2 jul 2024 om 09:26 schreef Gopi ***@***.***>:

**Comment by Kris3D** [comment] 2024-07-02 18:12
Installed J2Store4 on a new Joomla 4 site. Same problem.

**Comment by mgopin3** [comment] 2024-07-03 09:26
@Kris3D I recommend submitting a support ticket to the J2Store support team,Using this email [support@j2store.org](mailto:support@j2store.org). Please include your admin login details and FTP information for a more efficient resolution from our end.

**Comment by mgopin3** [comment] 2024-07-29 10:50
@Kris3D We have successfully resolved the issue on your site as per the ticket you raised. The code changes are now live, and standard shipping will be listed without any issues. We have also noted this issue and will address it in the upcoming J2Store v4.x.x release. Thank you for your understanding.For your reference, please check the commit changes #118

 We believe the reported issue has been addressed. Could you please confirm that the problem is resolved on your end? If everything looks good, we'll go ahead and close this issue.

If you have any further questions or if there's anything else you'd like assistance with, please don't hesitate to let us know. We appreciate your feedback!

**Comment by Kris3D** [comment] 2024-07-31 06:57
This is great! Thank you.

**Closed as completed** 2024-08-06 05:22 UTC
