### ISSUE TITLE
Joomla Custom Fields not loaded

### ISSUE THREAD

**Issue by webgras** [J2Store4/j2store4#68] opened 2023-12-28 11:04 UTC
Joomla Custom fields are not loaded in the product single view.
It seems it is an app that is not yet available.

Any plans for implementation?

**Comment by mgopin3** [comment] 2024-01-02 05:07
I understand your concern. Currently, we do not have an option to display custom fields on the article single view, and we are not providing any apps for displaying the custom field. Please rest assured that we will take note of this issue.

**Comment by webgras** [comment] 2024-01-05 19:05
Yes please!
This was one of the main reasons, why we choose J2Store, because we can add custom fields to the products (articles).

**Comment by mgopin3** [comment] 2024-03-04 05:21
@webgras  Rest assured, we have taken note of your specific requirements, and we intend to address and incorporate the mentioned issue in an upcoming release.
Hope your understand.

**Comment by mgopin3** [comment] 2024-03-08 05:54
@webgras We believe the reported issue has been addressed. Could you please confirm that the problem is resolved on your end? If everything looks good, we'll go ahead and close this issue.

If you have any further questions or if there's anything else you'd like assistance with, please don't hesitate to let us know. We appreciate your feedback!

**Closed as completed** 2024-03-12 04:49 UTC
