### ISSUE TITLE
Not displaying product in user and administrator order list

### ISSUE THREAD

**Issue by niaziblog** [J2Store4/j2store4#77] opened 2024-01-25 19:59 UTC
hello,
I encountered a very strange problem in j2store،
Recently, I noticed that some products that are purchased are not displayed user list of orders and administrator order lists.

Where is the problem now? I found this problem but it is strange why j2store should have such a strange problem

![currency](https://github.com/J2Store4/j2store4/assets/16794117/18494a2c-d684-4357-9080-fd52a38f6ba2)

The j2store currency is IRR and The decimal point is set to zero
When I enter the price of a product less than 10,000,000 IRR (for example 9,999,999), this product will be displayed in the user's orders list and administrator , after purchase.
**This is the same problem for all currencies**

![currency1](https://github.com/J2Store4/j2store4/assets/16794117/35b3db14-67a8-430c-8cc2-86882dc80121)
![currency2](https://github.com/J2Store4/j2store4/assets/16794117/9bedfc6e-be4d-4c3d-a67c-e6d8f25b07ce)

But when you enter the price of the product more than 10,000,000 IRR, this product is not displayed in the user's order list on the site and administration.
All the payment steps and purchase amount are correct. Only the product whose price is more than 9،999،999 will not be displayed in orders.
I have prepared a picture and video for this problem and you can see this problem, from j2store version 40.0 to the latest version i.e. 4.0.4 this problem exists

**video link : https://drive.google.com/file/d/198_vvO1AjH4H2QGfQUhed49Dl1PLGuWc/view?usp=sharing**
Note : In this video I have Create 2 products. The first product has a price of 9،999،999 Rial and the second product has a price of 10،000،000 Rial. As you can see in the video, the product that has a price of 9،999،999 Rial is displayed in the list of orders, but the second product that has a price of 10،000،000 Rial is not displayed in the user and administrator orders list.

How to solve this strange problem? Why should there be this limitation in j2store?

**Comment by niaziblog** [comment] 2024-02-07 12:54
@mgopin3 @rameshelamathi 
Please check this issue .Because this problem has involved several stores.
 I have fully described this issue
This problem exists in all versions of the J2store
Thanks alot...

**Comment by mgopin3** [comment] 2024-03-04 01:43
@niaziblog I appreciate your concern. Rest assured, we will take note of this issue and address it in the upcoming J2Store release. Your understanding is valued

**Comment by mgopin3** [comment] 2024-04-01 04:47
@niaziblog We believe the reported issue has been addressed. Could you please confirm that the problem is resolved on your end? If everything looks good, we'll go ahead and close this issue.

If you have any further questions or if there's anything else you'd like assistance with, please don't hesitate to let us know. We appreciate your feedback!

**Comment by niaziblog** [comment] 2024-04-01 07:16
@mgopin3 You said that this problem will be fixed in the next version, but there is no version yet that I can check if this problem is solved or not.

Due to this problem, many of our sites are not able to sell because the purchased product is not displayed in the list of user and administrator products

**Comment by mgopin3** [comment] 2024-04-05 07:24
@niaziblog We appreciate your bringing this issue to our attention, and rest assured, it will be resolved in the forthcoming J2Store release. Your understanding and patience are greatly appreciated.

**Comment by mgopin3** [comment] 2024-04-22 05:18
@niaziblog We would like to inform you that typically, we restrict purchases exceeding 9 million units. However, if you wish to allow purchases exceeding this limit, you can resolve the issue by adjusting the database. Navigate to the 'j2store_orderitems' table, and in the 'orderitem_price' column, change the data type from 'decimal(12,5)' to 'decimal(12,4)'. Once this adjustment is complete, the issue will be resolved.Hope you understand .

**Comment by mgopin3** [comment] 2024-04-23 11:47
@niaziblog Thankyou for your understand and patience.
we will consider your requirement as feedback, and we will incorporate it into our upcoming J2Store release. If everything looks good, we'll go ahead and close this issue.

If you have any further questions or if there's anything else you'd like assistance with, please don't hesitate to let us know. We appreciate your feedback!

**Comment by niaziblog** [comment] 2024-04-23 13:42
@mgopin3 Thank you very much.
Below solution , fixed my problem, but I hope you fix it in next version j2store,  so that more people don't get misled by this problem.
Thanks

**Navigate to the 'j2store_orderitems' table, and in the 'orderitem_price' column, change the data type from 'decimal(12,5)' to 'decimal(12,4)'. **

**Closed as completed** 2024-04-23 15:49 UTC
