### ISSUE TITLE
After update to J4, new products are not shown in product list in backend

### ISSUE THREAD

**Issue by webgras** [J2Store4/j2store4#35] opened 2023-10-09 08:42 UTC
We just did an upgrade to J4.
The products are not shown in the frontend (not in Casseiopeia and not in Yootheme)
I tried to add a new product (simple) in the backend. This is not recognised as product in my J2store product list.
I cannot set a price because the variant ID is missing, but I don't have(need) variants.
![grafik](https://github.com/J2Store4/j2store4/assets/10774704/df47eb4f-b863-44d5-935a-28000932696f)
![grafik](https://github.com/J2Store4/j2store4/assets/10774704/16225960-0938-4302-9e0e-da601b2a3515)
![grafik](https://github.com/J2Store4/j2store4/assets/10774704/eadc2f9e-7d5d-497a-8477-0b4a2adbc1a4)
![grafik](https://github.com/J2Store4/j2store4/assets/10774704/52ab0075-806d-4269-812b-7263afae2b6d)

**Comment by angieradtke** [comment] 2023-12-05 17:33
Hi ,
the same issue here.  @webgras  we will get no answer here.  It must be  a database issue. 
#

**Comment by angieradtke** [comment] 2023-12-06 15:34
Solved . Structure of j2store_variants  is not updated to the new structure.  Column shipping was missing and column params and sold whre old  and needless

CREATE TABLE IF NOT EXISTS `#__j2store_variants` (
  `j2store_variant_id` int(11) NOT NULL AUTO_INCREMENT,
  `product_id` int(11) DEFAULT NULL,
  `is_master` int(11) DEFAULT NULL,
  `sku` varchar(255) DEFAULT NULL,
  `upc` varchar(255) DEFAULT NULL,
  `price` decimal(15,5) DEFAULT NULL COMMENT 'Regular price of the product',
  `pricing_calculator` varchar(255) NOT NULL,
  `shipping` int(11) NOT NULL,
  `length` decimal(15,5) DEFAULT NULL,
  `width` decimal(15,5) DEFAULT NULL,
  `height` decimal(15,5) DEFAULT NULL,
  `length_class_id` int(11) DEFAULT NULL,
  `weight` decimal(15,5) DEFAULT NULL,
  `weight_class_id` int(11) DEFAULT NULL,  
  `created_on` varchar(255) DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `modified_on` varchar(45) DEFAULT NULL,
  `modified_by` int(11) DEFAULT NULL,
  `manage_stock` int(11) DEFAULT NULL,
  `quantity_restriction` int(11) NOT NULL,
  `min_out_qty` decimal(15,5) DEFAULT NULL,
  `use_store_config_min_out_qty` int(11) DEFAULT NULL,
  `min_sale_qty` decimal(15,5) DEFAULT NULL,
  `use_store_config_min_sale_qty` int(11) DEFAULT NULL,
  `max_sale_qty` decimal(15,5) DEFAULT NULL,
  `use_store_config_max_sale_qty` int(11) DEFAULT NULL,
  `notify_qty` decimal(15,5) DEFAULT NULL,
  `use_store_config_notify_qty` int(11) DEFAULT NULL,
  `availability` int(11) DEFAULT NULL,
  `allow_backorder` int(11) NOT NULL,  
  `isdefault_variant` int(11) NOT NULL,
  PRIMARY KEY (`j2store_variant_id`),
  KEY `variant_product_id` (`product_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

**Comment by mgopin3** [comment] 2024-03-01 02:26
I appreciate your understanding and patience. Typically, upon installing our J2Store application as mentioned earlier, the table structure remains intact. Upon completion, when accessing your dashboard, a script will be rendered which will subsequently add additional columns to several tables. As a result, upon reaching your dashboard, the "sold," "params," and "upc" columns will be seamlessly integrated into your variants table. This process effectively resolves the issue at hand. 
Thank you for your cooperation and understanding.

**Comment by mgopin3** [comment] 2024-03-08 06:04
@mgopin3 We believe the reported issue has been addressed. Could you please confirm that the problem is resolved on your end? If everything looks good, we'll go ahead and close this issue.

If you have any further questions or if there's anything else you'd like assistance with, please don't hesitate to let us know. We appreciate your feedback!

**Comment by twdjo** [comment] 2024-03-08 15:04
I am having this same issue with not being able to save various fields in new products (i.e. SKU, prices). I also determined that it is an issue with the new items not being added to the j2store_variants table. Can you detail exactly how to fix the issue?

**Comment by twdjo** [comment] 2024-03-08 18:09
@mgopin3 Many thanks for the solution!

**Closed as completed** 2024-03-12 04:50 UTC
