### ISSUE TITLE
Direct Checkout plugin for J2store4

### ISSUE THREAD

**Issue by pulsarinformatique** [J2Store4/j2store4#70] opened 2024-01-01 10:07 UTC
Hello

I'm sorry but we do need the DIrect Checkout  plugin asap please!

We have several sites we can't migrate because of this missing plugin. 

thanks

cyril

**Comment by mgopin3** [comment] 2024-01-02 05:13
We would like to inform you that we have recently migrated and released **'Easy Checkout'** compatibility for Joomla 4 with J2Store 4. If you are interested in purchasing the **'Easy Checkout'** component, you can find the link to buy the latest release with Joomla 4 compatibility here: https://www.j2store.org/downloads/easy-checkout/

**Comment by pulsarinformatique** [comment] 2024-01-02 07:06
Hello
is it the same thing as the previous DirectCheckout that bypassed the cart stage ?

thanks

**Comment by mgopin3** [comment] 2024-01-05 05:40
Indeed, your observation is accurate. The recently introduced **'Easy Checkout'** component mirrors the efficiency of a one-page checkout, seamlessly presenting all facets of a standard checkout process. This includes comprehensive details such as basket contents, billing and shipping addresses, shipping options, and payment information—all conveniently consolidated on a single page. We appreciate your inquiry

**Comment by pulsarinformatique** [comment] 2024-01-05 08:13
Ok thanks
I installed it on a J4 migrated project where the former DirectCheckout app was installed but deactivated.
now in the J2store apps I still can't find the easycheckout app. Is that normal ? should I unsintall the former directcheckout ?
thanks

**Comment by pulsarinformatique** [comment] 2024-01-09 16:25
Hello
Can you answer please?
I installed it on a J4 migrated project where the former DirectCheckout app was installed but deactivated.
now in the J2store apps I still can't find the easycheckout app. Is that normal ? should I unsintall the former directcheckout ?
thanks

**Comment by pulsarinformatique** [comment] 2024-01-12 07:52
Hello
Can you answer please?
I installed it on a J4 migrated project where the former DirectCheckout app was installed but deactivated.
now in the J2store apps I still can't find the easycheckout app. Is that normal ? should I unsintall the former directcheckout ?
thanks

**Comment by pulsarinformatique** [comment] 2024-02-05 13:26
Hello
We badly need your answer please : I installed it on a J4 migrated project where the former DirectCheckout app was installed but deactivated.
now in the J2store apps I still can't find the easycheckout app. Is that normal ? should I unsintall the former directcheckout ?
thanks

**Comment by mgopin3** [comment] 2024-03-04 05:10
I appreciate your concern. Allow us to inform you that the Easy Checkout component is typically located under 'Components' -> 'J2Store Easy Checkout.' For your reference, kindly review this image: [[provide image link or description](https://tinyurl.com/ymsmm5hl)].

Please ensure that you are utilizing the latest version of the 4.x.x Easy Checkout on your site. If you are currently employing an older version of Easy Checkout, please be aware that it may automatically deactivate on your Joomla 4 site.

**Comment by mgopin3** [comment] 2024-03-08 05:52
@pulsarinformatique We believe the reported issue has been addressed. Could you please confirm that the problem is resolved on your end? If everything looks good, we'll go ahead and close this issue.

If you have any further questions or if there's anything else you'd like assistance with, please don't hesitate to let us know. We appreciate your feedback!

**Closed as completed** 2024-03-12 04:31 UTC
