### ISSUE TITLE
Zones/Regions only show US states when entering guest addresses

### ISSUE THREAD

**Issue by Kris3D** [J2Store4/j2store4#115] opened 2024-07-02 13:19 UTC
When entering your address as a guest customer the Zones/Regions fiels only show US states no matter which country is chosen. If the default country within the custom field is changed, then only the zones from that country are displayed.

So the Zones field doensn't show the relevant zones to the chosen country.

**Comment by mgopin3** [comment] 2024-07-03 09:46
@Kris3D Based on your request, we have reviewed our site and can confirm that the zones are updating correctly based on the selected country. For your reference, please check this video:- https://www.awesomescreenshot.com/video/29203297?key=f142e85f8725f879eee6323829820401

**Comment by mgopin3** [comment] 2024-07-29 12:02
@Kris3D We have successfully resolved the issue on your site as per the ticket you raised. Now, the zone will change based on the selected country without any issues. Thank you for your understanding.

We believe the reported issue has been addressed. Could you please confirm that the problem is resolved on your end? If everything looks good, we'll go ahead and close this issue.

If you have any further questions or if there's anything else you'd like assistance with, please don't hesitate to let us know. We appreciate your feedback!

**Closed as completed** 2024-08-06 05:22 UTC
