### ISSUE TITLE
import export issue

### ISSUE THREAD

**Issue by GeertF** [J2Store4/j2store4#101] opened 2024-04-01 10:49 UTC
Using J2Store 4.0.4 and import export plugin 1.16 in Joomla4

Yesterday I noticed that the import/export plugin is not working anymore. If it would be useful I would update to version 1.17 but it´s not possible to download that anymore on the J2store website. What would be the solution?

**Comment by mgopin3** [comment] 2024-04-03 06:07
@GeertF We regret to inform you that the Simple CSV Import/Export app is currently not compatible with J2store4 in Joomla 4. However, we have successfully migrated and released several payment and shipping apps, components, and modules that are fully compatible with J2store4.

We appreciate your requirement and assure you that we will take note of it. Our team will consider migrating this plugin and integrating it into our J2store release as soon as possible. We apologize for any inconvenience this may cause and thank you for your understanding.

**Comment by mgopin3** [comment] 2024-04-15 04:52
@GeertF Thankyou for your understand and patience.
we will consider your requirement as feedback, and we will incorporate it into our upcoming J2Store release. If everything looks good, we'll go ahead and close this issue.

If you have any further questions or if there's anything else you'd like assistance with, please don't hesitate to let us know. We appreciate your feedback!

**Comment by davcraiguk** [comment] 2024-04-18 22:19
There is a mature 3rd party import/export component that that works with all product types and all fields of j2store. I use it to generate Google merchant CSV (or xlsx) files, update prices, descriptions. You can also run export/imports on a cron. you can find it [here](https://rolandd.com/products/ro-csvi)

**Comment by mgopin3** [comment] 2024-04-22 05:29
@davcraiguk I understand your concern. Currently, we do not have the option to recommend any third-party plugins. However, if you wish to utilize a third-party import/export plugin that works for you, you are free to do so. Additionally, I would like to inform you that our team will consider migrating and integrating this plugin into our J2store release as soon as possible.

**Comment by mgopin3** [comment] 2024-07-29 12:11
@GeertF, we would like to inform you that we have successfully migrated and released the **Import/Export** plugin for J2Store 4. If you are interested in viewing and purchasing our latest Import/Export plugin, please use this link: [Link](https://www.j2store.org/downloads/simple-csv-import/). Thank you for your understanding.

We believe the reported issue has been addressed. Could you please confirm that the problem is resolved on your end? If everything looks good, we'll go ahead and close this issue.

If you have any further questions or if there's anything else you'd like assistance with, please don't hesitate to let us know. We appreciate your feedback!

**Closed as completed** 2024-08-21 05:41 UTC
