### ISSUE TITLE
Error loading css file module mod_j2store_cart

### ISSUE THREAD

**Issue by trantrongthang1207** [J2Store4/j2store4#36] opened 2023-10-12 09:10 UTC
I upgraded j2store for Joomla 4. Because of this error, my site loaded very slowly
old code: $platform->addStyle('j2store-cart','modules/mod_j2store_cart/css/j2store_cart.css');
new code: $platform->addStyle('j2store-cart','/modules/mod_j2store_cart/css/j2store_cart.css');

**Comment by mgopin3** [comment] 2023-10-18 05:02
Thank you for bringing this issue to our attention. Please don't worry, we will treat this as valuable feedback. We intend to address and resolve this issue in an upcoming release of J2Store4. You can refer to the commit code changes on J2Store4 for more information #39

**Comment by mgopin3** [comment] 2024-03-05 04:52
@trantrongthang1207 We believe the reported issue has been addressed. Could you please confirm that the problem is resolved on your end? If everything looks good, we'll go ahead and close this issue.

If you have any further questions or if there's anything else you'd like assistance with, please don't hesitate to let us know. We appreciate your feedback!

**Closed as completed** 2024-03-05 08:51 UTC
