### ISSUE TITLE
Download Item issue

### ISSUE THREAD

**Issue by coolcat-creations** [J2Store4/j2store4#14] opened 2023-08-23 13:20 UTC
I am referring to this issue: https://github.com/J2Store4/j2store4/pull/7#issuecomment-1689365621
can you fix this?

**Comment by mgopin3** [comment] 2023-10-18 10:10
I understand your concern. We have conducted tests on our local site and confirmed that the downloadable product path is functioning correctly, with downloads occurring without any issues. We have also thoroughly reviewed the code, and all conditions related to the download path are working properly.

Therefore, it's possible that the issue may be due to the file path not existing on your site. Please verify whether the path exists on your site or not. For your reference, please view this video: https://www.awesomescreenshot.com/video/21689182?key=68e41a93e57599e05319a3d590c76a9d.

**Comment by mgopin3** [comment] 2024-03-05 05:26
@coolcat-creations We believe the reported issue has been addressed. Could you please confirm that the problem is resolved on your end? If everything looks good, we'll go ahead and close this issue.

If you have any further questions or if there's anything else you'd like assistance with, please don't hesitate to let us know. We appreciate your feedback!

**Comment by coolcat-creations** [comment] 2024-03-05 17:45
I dont know because I corehacked the file, can you direct me to the change that had been done so I can check?

**Comment by mgopin3** [comment] 2024-03-08 07:09
@coolcat-creations Navigate to J2Store -> Setup -> Configuration. In the Basic Settings tab, locate the "Folder Path for Digital Goods" field [[Image](https://tinyurl.com/2dxyypww)].In this field, specify the folder path that corresponds to the location of the files you typically select in the Files section when configuring Downloadable Products. After a purchase, the system will verify the file extension under the specified "Folder Path for Digital Goods" to ensure the existence of the file before displaying the download button and initiating the download process. This validation step ensures a seamless and secure download experience for customers.Hope you understand

**Comment by coolcat-creations** [comment] 2024-03-08 08:55
No, I meant can you show me the line you fixed in j2Store (php) so I can compare with the core hacked version?

**Comment by mgopin3** [comment] 2024-03-12 05:37
@coolcat-creations This relates to the file located at the following path: /administrator/components/com_j2store/models/orderdownloads.php, specifically in the getFilePath() function around line 399. In this function, we have implemented a check to verify the existence of the file path before displaying the download button and initiating the download process.

**Comment by mgopin3** [comment] 2024-03-14 07:50
@coolcat-creations We believe the reported issue has been addressed. Could you please confirm that the problem is resolved on your end? If everything looks good, we'll go ahead and close this issue.

If you have any further questions or if there's anything else you'd like assistance with, please don't hesitate to let us know. We appreciate your feedback!

**Closed as completed** 2024-03-21 09:50 UTC
