### ISSUE TITLE
Compatibility Bug with J2Store & Gantry 5 Inherited Particle and Section Issue when clicking cog wheel

### ISSUE THREAD

**Issue by N8Solutions** [J2Store4/j2store4#46] opened 2023-11-03 14:02 UTC
Hello, I've found a bug.

There's an issue after installing J2Store on a website that is using the Gantry 5 Framework. When you try to click on a "cog" for a Gantry 5 particle or section that is inheriting it's settings from another layout. You end up getting the errors seen in the images below. If I uninstall J2Store the problem goes away.

It happens with PHP v8.0, v8.1, & v8.2.
Latest version of  Joomla 4.x & 3.x
I've tried going back several versions of Gantry 5 but nothing changes. The issue is still present with J2Store going back to v4.0.0. I don't know what the incompatibility is, or who's side it is on, I just know it exists and this error happens when both are installed.

I already had an existing issue opened with Gantry 5 on this, and now that I discovered it has to do with J2Store I'm opening this one and referencing the other. https://github.com/gantry/gantry5/issues/3199

**On Joomla 3.x you see this:**
![Screenshot 2023-10-31 at 21-23-12 Mission Life Georgia - Administration](https://github.com/gantry/gantry5/assets/12389693/c2c304e4-85ab-4985-979b-d5581ce4e3a4)

**On Joomla 4.x you see this:**
![Screenshot 2023-10-31 at 21-43-22 Gantry 5 Helium J4 - Administration](https://github.com/gantry/gantry5/assets/12389693/57bcafc7-2658-46fe-8d8f-a7d21f6c7efc)

**Comment by JoomFX** [comment] 2023-11-04 09:03
Yep, @N8Solutions is right. I was able to reproduce the issue.
Here's a [short video](https://youtu.be/M9grhcCZ9rQ).

**Comment by Thomastomy2001** [comment] 2023-11-22 06:20
We installed Gantry5 and J2Store 4, but we were unable to reproduce the issue. It was working without any conflicts(check this video:https://nimb.ws/pD8cQG). Maybe this issue occurred because of the themes you have in your site. Could you please check if they are compatible with the latest Joomla and J2Store versions?

**Comment by N8Solutions** [comment] 2023-11-30 09:51
@Thomastomy2001 Thank you for looking but you are not recreating the issue properly. Please try again after you have reviewed the video that @JoomFX posted.
[https://youtu.be/M9grhcCZ9rQ](https://youtu.be/M9grhcCZ9rQ)

Note that the Gantry 5 particle or section must already be inherited, i.e. showing what "outline" it is being inherited and it will also have the diagonal lines running through it.

I believe once you do this you will see the issue we are discussing.


kind regards

**Comment by N8Solutions** [comment] 2023-12-09 19:05
@rameshelamathi Can you take a look at this?

I understand you guys are busy but there are some important issues, like this one, that really need to be addressed. The least you guys can do is acknowledge the issue has been opened.

**Comment by mgopin3** [comment] 2023-12-14 04:41
I understand your concern. 
Upon reviewing your video reference, we found that you are currently using Joomla 4 with the Gantry 5 framework and the Delight theme on your site. Upon checking the Delight theme, we discovered that it is only compatible with Joomla 3 ,For your reference please check this Delight theme compatiblity:- https://www.inspiretheme.com/joomla-templates/delight . This is likely the reason for the issues you are encountering.

In this case, I recommend checking with a different theme for the Gantry 5 framework that is compatible with Joomla 4. We also verified on our Joomla 4 site that, by installing the Gantry 5 framework with the Hydrogen theme, it worked without any issues. Please ensure that the problem is not related to our J2Store extension.

**Comment by JoomFX** [comment] 2023-12-14 10:14
@mgopin3 I am the developer of the Delight template and the founder of InspireTheme.
We have a BETA version of the Delight template, which is available for download in our support forum only, which is Joomla 4 compatible and does not include the J2Store extension.
The only thing that prevents us from officially releasing the J4/J5 version of the Delight template is the J2Store extension and more precisely [this issue](https://github.com/J2Store4/j2store4/issues/40).

Now, coming back to the original issue discussed here - the issue is a conflict between the Gantry 5 framework and the J2Store extension. It has nothing to do with the template.
Here, please have a look at [this new video](https://youtu.be/2ZnYyhKdYpM) that I recorded for you.
It is a default installation of the Gantry 5 framework (with the default Helium template).

**Comment by N8Solutions** [comment] 2023-12-14 10:31
@JoomFX Thank you for replying. Since I previously had a Pro Developer license for J2Store, I had support available with them and opened a ticket for this at the same time I opened the issue here. I replied to them with the same information. Your video highlights the issue exactly, so thank you again for making it. I have updated my ticket with them to inform them of your reply here. Hopefully @mgopin3 & @rameshelamathi will see this so they can take care of it asap.

**Comment by mgopin3** [comment] 2023-12-18 06:47
Thank you for bringing this issue to our attention. Please rest assured that we take this matter seriously. We consider your feedback valuable, and we are committed to resolving this compatibility issue promptly. The necessary fixes will be implemented and included in the upcoming J2Store release. For your reference, you can review the details in this commit pull request on our J2Store repository. Your patience and understanding are greatly appreciated. #64

**Comment by N8Solutions** [comment] 2023-12-18 08:53
Thank you for the reply @mgopin3, I look forward to testing out the new release once it is ready.

**Comment by mgopin3** [comment] 2024-03-05 02:02
@JoomFX @N8Solutions We believe the reported issue has been addressed. Could you please confirm that the problem is resolved on your end? If everything looks good, we'll go ahead and close this issue.

If you have any further questions or if there's anything else you'd like assistance with, please don't hesitate to let us know. We appreciate your feedback!

**Closed as completed** 2024-03-13 02:43 UTC
Labels: help wanted, looking for volunteers from community
