### ISSUE TITLE
Update for plugin (Download button) such as SagePay broken

### ISSUE THREAD

**Issue by exlemor** [J2Store4/j2store4#30] opened 2023-10-01 23:12 UTC
Even on v4.0.3 pro, J2Store claims that there is an updated plugin version 3.15 [vs 3.13 which is installed] and it shows a 
Download button - (see screenshot) when you click on that Download button it sends you to:

http://www.domainname.com/administrator/index.php?option=com_j2store&view=eupdates ---> 

https://www.j2store.org/my-downloads.html?utm_source=pro&utm_medium=component&utm_campaign=inline&utm_content=update

and a nice 404 error page.

![screenshot_2342](https://github.com/J2Store4/j2store4/assets/2597232/e663227d-a5ac-4628-aa21-76b31a5c789c)

**Comment by mgopin3** [comment] 2023-10-06 12:25
I understand your concern.

I would like to inform you that we have currently removed the update section from J2Store4. This decision was made because the SagePay Form payment plugin will now be included as an inbuilt payment plugin in J2Store4. We are currently using the latest version, 3.15, of SagePay Form with J2Store4.

When we release new updates for J2Store4.x.x versions, the inbuilt SagePay Form plugin will also be updated, just like a Joomla update. You can refer to this commit on J2Store4 for your reference, where we removed the update section:https://github.com/J2Store4/j2store4/pull/33

**Comment by mgopin3** [comment] 2024-03-05 04:55
@exlemor  We believe the reported issue has been addressed. Could you please confirm that the problem is resolved on your end? If everything looks good, we'll go ahead and close this issue.

If you have any further questions or if there's anything else you'd like assistance with, please don't hesitate to let us know. We appreciate your feedback!

**Closed as completed** 2024-03-12 04:51 UTC
