### ISSUE TITLE
Problem in inserting a space in the email

### ISSUE THREAD

**Issue by mehdininja** [J2Store4/j2store4#91] opened 2024-03-13 01:48 UTC
In some buyers' emails, a space is inserted at the end!
"test@test.com "

There is no problem in login guest, but there is an error in viewing and printing the invoice.

![jprint](https://github.com/J2Store4/j2store4/assets/74552816/4bd6b062-29b6-48fe-b120-30b738483cf9)

![jem](https://github.com/J2Store4/j2store4/assets/74552816/0c1ee10e-46eb-4f61-bff6-e3a183cea0ed)

By removing the space from the end of the email, the problem is solved. But why is this space added in some emails?

**Comment by mgopin3** [comment] 2024-03-13 07:40
@mehdininja We have verified that our guest user login functionality is operating smoothly. Upon examination, we ensure that entering spaces at the end of the guest email address triggers an error prompt, preventing login and prompting users to input a valid email. For further clarification, please refer to the provided video demonstration:- https://www.awesomescreenshot.com/video/25764563?key=f94e3ab1f444df14d413b69da2f21369

**Comment by mehdininja** [comment] 2024-03-13 15:58
@mgopin3  Please watch this video I recorded to understand the problem

https://github.com/J2Store4/j2store4/assets/74552816/c48280c8-0227-4b2b-947f-f6ebe1e9b7ad

**Comment by mgopin3** [comment] 2024-03-14 06:47
@mehdininja Typically, we verify that the email and token associated with an order match before allowing access to view the invoice. It appears that there is an extra white space appended to the email address in your order table. Consequently, when attempting to view the invoice, our validation process detects this discrepancy and returns an error message. Please be assured that we have taken note of this issue and plan to address it in the upcoming release of J2Store 4.x.x. For your reference, please review the committed code changes in our J2Store repository:- https://github.com/J2Store4/j2store4/pull/92/files

**Comment by mgopin3** [comment] 2024-03-22 12:00
@mehdininja We believe the reported issue has been addressed. Could you please confirm that the problem is resolved on your end? If everything looks good, we'll go ahead and close this issue.

If you have any further questions or if there's anything else you'd like assistance with, please don't hesitate to let us know. We appreciate your feedback!

**Closed as completed** 2024-03-28 04:57 UTC
